# Generated by Django 5.2.8 on 2025-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_programoutcome_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programoutcome',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='grade',
            name='course_name',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ProgramOutcome',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
