# Generated by Django 5.2.1 on 2025-12-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programoutcome',
            name='related_program_outcomes',
            field=models.ManyToManyField(blank=True, related_name='learning_outcomes', to='core.programoutcome'),
        ),
    ]
