# Generated by Django 5.2.1 on 2025-12-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_department_remove_course_year_and_more'),
        ('core', '0006_programoutcome_related_program_outcomes'),
    ]

    operations = [
    ]
