# Generated by Django 5.2.9 on 2025-12-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_department_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.course'),
        ),
    ]
