# Generated by Django 6.0 on 2025-12-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_announcement_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grades',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course')},
        ),
    ]
