# Generated by Django 5.2.9 on 2025-12-26 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_relationships(apps, schema_editor):
    ProgramOutcome = apps.get_model('core', 'ProgramOutcome')
    LearningOutcomeProgramOutcome = apps.get_model('core', 'LearningOutcomeProgramOutcome')
    
    for lo in ProgramOutcome.objects.all():
        for po in lo.related_program_outcomes.all():
            LearningOutcomeProgramOutcome.objects.get_or_create(
                learning_outcome=lo,
                program_outcome=po,
                defaults={'percentage': 0}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_po_relationships', to='core.programoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lo_relationships', to='core.programoutcome')),
            ],
            options={
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
        migrations.RunPython(migrate_existing_relationships),
        migrations.RemoveField(
            model_name='programoutcome',
            name='related_program_outcomes',
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='related_program_outcomes',
            field=models.ManyToManyField(blank=True, related_name='learning_outcomes', through='core.LearningOutcomeProgramOutcome', to='core.programoutcome'),
        ),
    ]
