# Generated by Django 5.2.8 on 2025-12-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_learningoutcomeprogramoutcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_counts',
            field=models.JSONField(default=dict),
        ),
    ]
