# Generated by Django 5.2.8 on 2025-12-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_assessment_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_counts',
        ),
    ]
