# Generated by Django 5.2.8 on 2025-12-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_course_assessment_counts'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_grade RENAME COLUMN assessment TO assignment;",
            reverse_sql="ALTER TABLE core_grade RENAME COLUMN assignment TO assessment;",
        ),
    ]
