# Generated by Django 5.2.8 on 2025-12-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_assessment_to_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm', models.IntegerField(default=2)),
                ('final', models.IntegerField(default=1)),
                ('proje', models.IntegerField(default=0)),
                ('homework', models.IntegerField(default=0)),
                ('absence', models.IntegerField(default=0)),
                ('assessment_count', models.IntegerField(default=3)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='core.course')),
            ],
        ),
    ]
