# Generated by Django 5.2.8 on 2025-12-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='absence_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='final_percentage',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='assessment',
            name='homework_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='midterm_percentage',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proje_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quiz_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
