# Generated by Django 5.2.8 on 2025-12-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assessment_absence_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='final',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='finalized_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='midterm',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='uploaded_file_name',
        ),
    ]
