# Generated by Django 5.2.7 on 2025-12-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_advisor'),
        ('core', '0019_assessment_absence_percentage_and_more'),
    ]

    operations = [
    ]
