# Generated by Django 5.2.8 on 2025-12-27 10:24

from django.db import migrations, models


def convert_float_to_json_forward(apps, schema_editor):
    """Convert float values to JSON (null or float)"""
    Grade = apps.get_model('core', 'Grade')
    for grade in Grade.objects.all():
        # Convert float fields to JSON (null or float value)
        for field_name in ['absence', 'final', 'homework', 'midterm', 'proje', 'quiz']:
            value = getattr(grade, field_name)
            if value is not None:
                # Keep the float value
                setattr(grade, field_name, float(value))
            else:
                setattr(grade, field_name, None)
        grade.save()


def convert_float_to_json_sql(schema_editor):
    """Convert float to jsonb using SQL"""
    # PostgreSQL: Convert double precision to jsonb via text
    # NULL stays NULL, numeric values become JSON numbers
    for field in ['absence', 'final', 'homework', 'midterm', 'proje', 'quiz']:
        schema_editor.execute(
            f'''
            ALTER TABLE "core_grade" 
            ALTER COLUMN "{field}" TYPE jsonb 
            USING CASE 
                WHEN "{field}" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("{field}"::text::numeric)
            END;
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_grade_fields'),
    ]

    operations = [
        # Convert data using SQL (PostgreSQL specific)
        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_grade" 
            ALTER COLUMN "absence" TYPE jsonb 
            USING CASE 
                WHEN "absence" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("absence"::text::numeric)
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "final" TYPE jsonb 
            USING CASE 
                WHEN "final" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("final"::text::numeric)
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "homework" TYPE jsonb 
            USING CASE 
                WHEN "homework" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("homework"::text::numeric)
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "midterm" TYPE jsonb 
            USING CASE 
                WHEN "midterm" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("midterm"::text::numeric)
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "proje" TYPE jsonb 
            USING CASE 
                WHEN "proje" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("proje"::text::numeric)
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "quiz" TYPE jsonb 
            USING CASE 
                WHEN "quiz" IS NULL THEN NULL::jsonb
                ELSE to_jsonb("quiz"::text::numeric)
            END;
            """,
            reverse_sql="""
            ALTER TABLE "core_grade" 
            ALTER COLUMN "absence" TYPE double precision 
            USING CASE 
                WHEN "absence" IS NULL THEN NULL::double precision
                ELSE ("absence"::text)::double precision
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "final" TYPE double precision 
            USING CASE 
                WHEN "final" IS NULL THEN NULL::double precision
                ELSE ("final"::text)::double precision
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "homework" TYPE double precision 
            USING CASE 
                WHEN "homework" IS NULL THEN NULL::double precision
                ELSE ("homework"::text)::double precision
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "midterm" TYPE double precision 
            USING CASE 
                WHEN "midterm" IS NULL THEN NULL::double precision
                ELSE ("midterm"::text)::double precision
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "proje" TYPE double precision 
            USING CASE 
                WHEN "proje" IS NULL THEN NULL::double precision
                ELSE ("proje"::text)::double precision
            END;
            
            ALTER TABLE "core_grade" 
            ALTER COLUMN "quiz" TYPE double precision 
            USING CASE 
                WHEN "quiz" IS NULL THEN NULL::double precision
                ELSE ("quiz"::text)::double precision
            END;
            """
        ),
        # Update model field definitions
        migrations.AlterField(
            model_name='grade',
            name='absence',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homework',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='proje',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
