# Generated by Django 5.2.8 on 2025-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_change_grade_fields_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='absence',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homework',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='proje',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
