# Generated by Django 5.2.8 on 2025-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_change_grade_fields_to_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assessment_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
