# Generated by Django 5.2.8 on 2025-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_assessment_scores_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='last_changes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
