# Generated by Django 6.0 on 2025-12-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20251227_1433'),
        ('core', '0025_add_last_changes_at'),
    ]

    operations = [
    ]
