# Generated by Django 5.2.9 on 2025-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20251227_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='learningoutcomeprogramoutcome',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='learningoutcomeprogramoutcome',
            constraint=models.UniqueConstraint(fields=('learning_outcome', 'program_outcome'), name='unique_lo_po'),
        ),
    ]
