# Generated by Django 5.2.8 on 2025-12-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_proje_homework_to_project_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
