# Generated by Django 5.2.8 on 2025-12-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_grade_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
