# Generated by Django 5.2.9 on 2025-12-28 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_0029_grade_letter_grade_0029_merge_0027_add_course_name_unique_0028_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLORelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.IntegerField(default=0, help_text='Percentage contribution of this assessment to the learning outcome (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_relations', to='core.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_relations', to='core.programoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, help_text='Learning Outcomes that this assessment contributes to', related_name='assessments', through='core.AssessmentLORelation', to='core.programoutcome'),
        ),
        migrations.AddConstraint(
            model_name='assessmentlorelation',
            constraint=models.UniqueConstraint(fields=('assessment', 'learning_outcome'), name='unique_assessment_lo'),
        ),
    ]
