# Generated by Django 5.2.8 on 2025-12-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notification'),
        ('core', '0030_merge_0029_grade_letter_grade_0029_merge_0027_add_course_name_unique_0028_assignmentsubmission'),
    ]

    operations = [
    ]
