# Generated by Django 5.2.9 on 2025-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_assessment_lo_relation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentlorelation',
            name='unique_assessment_lo',
        ),
        migrations.AddField(
            model_name='assessmentlorelation',
            name='assessment_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('project', 'Project'), ('assignment', 'Assignment'), ('absence', 'Absence'), ('quiz', 'Quiz')], default='midterm', help_text='Type of assessment (midterm, final, project, etc.)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assessmentlorelation',
            constraint=models.UniqueConstraint(fields=('assessment', 'learning_outcome', 'assessment_type'), name='unique_assessment_lo_type'),
        ),
    ]
