# Generated by Django 5.2.9 on 2025-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_assessment_type_to_assessment_lo_relation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentlorelation',
            name='unique_assessment_lo_type',
        ),
        migrations.AddField(
            model_name='assessmentlorelation',
            name='assessment_index',
            field=models.IntegerField(default=1, help_text='Index of the assessment (1, 2, 3, etc.) - used to match with assessment_scores (e.g., midterm_1, midterm_2)'),
        ),
        migrations.AddConstraint(
            model_name='assessmentlorelation',
            constraint=models.UniqueConstraint(fields=('assessment', 'learning_outcome', 'assessment_type', 'assessment_index'), name='unique_assessment_lo_type_index'),
        ),
    ]
