# Generated by Django 5.2.9 on 2025-12-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_announcement_to_notification'),
        ('core', '0033_add_assessment_index_to_assessment_lo_relation'),
    ]

    operations = [
    ]
