# Generated by Django 5.2.9 on 2025-12-29 09:36

from django.db import migrations, models


def add_advisor_details(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('core', 'UserProfile')
    
    try:
        ahmet_bulut = User.objects.get(username='ahmet.bulut')
        profile, created = UserProfile.objects.get_or_create(user=ahmet_bulut)
        profile.advisor_details = 'Prof. Dr. Ahmet Bulut is a distinguished professor in the Computer Engineering department with extensive experience in software engineering, database systems, and computer architecture. He has been serving as an academic advisor for undergraduate students, providing guidance on course selection, career planning, and academic excellence. His research interests include distributed systems, data management, and educational technology.'
        profile.save()
    except User.DoesNotExist:
        pass
    
    try:
        ahmet_aydin = User.objects.get(username='ahmet.aydin')
        profile, created = UserProfile.objects.get_or_create(user=ahmet_aydin)
        profile.advisor_details = 'Prof. Dr. Ahmet Aydın is a distinguished professor in the Electrical Engineering department with extensive experience in electrical systems, power electronics, and circuit design. He has been serving as an academic advisor for undergraduate students, providing guidance on course selection, career planning, and academic excellence. His research interests include power systems, renewable energy, and electronic circuit design.'
        profile.save()
    except User.DoesNotExist:
        pass


def remove_advisor_details(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('core', 'UserProfile')
    
    try:
        ahmet_bulut = User.objects.get(username='ahmet.bulut')
        profile = UserProfile.objects.get(user=ahmet_bulut)
        profile.advisor_details = ''
        profile.save()
    except (User.DoesNotExist, UserProfile.DoesNotExist):
        pass
    
    try:
        ahmet_aydin = User.objects.get(username='ahmet.aydin')
        profile = UserProfile.objects.get(user=ahmet_aydin)
        profile.advisor_details = ''
        profile.save()
    except (User.DoesNotExist, UserProfile.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20251229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='advisor_details',
            field=models.TextField(blank=True, help_text='Detailed information about the advisor'),
        ),
        migrations.RunPython(add_advisor_details, remove_advisor_details),
    ]
