# Generated by Django 5.2.9 on 2025-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_advisor_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='receiver_role',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('faculty_head', 'Faculty Head'), ('student', 'Student')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sender_role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('faculty_head', 'Faculty Head'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
    ]
