# Generated by Django 5.2.9 on 2025-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_student_to_announcement_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Student email address for notifications', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Student phone number for SMS notifications', max_length=20, null=True),
        ),
    ]
